name: Bliss
description: "Bliss project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-180.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  iconsax: ^0.0.8
  flutter_native_splash: ^2.3.9
  google_maps_flutter: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  permission_handler: ^11.2.0
  open_apps_settings: ^0.0.4
  url_launcher: ^6.2.4
  webview_flutter: ^4.4.4
  geolocator: ^10.1.0
  flutter_polyline_points: ^1.0.0
  motion_tab_bar: ^2.0.4
  mobile_scanner: ^4.0.1


flutter_launcher_icons:
  image_path: "assets/logo.png"
  adaptive_icon_background: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
